version: "3.9"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: docusign_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: docusign_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://app:app@db:5432/docusign
      - NODE_ENV=production
      - JWT_SECRET=your_jwt_secret_here
      - PORT=3001
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/certificates:/app/certificates
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: docusign_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: docusign
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: docusign_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

volumes:
  db_data: {}
