services:
  - type: web
    name: docusign-backend
    env: node
    buildCommand: cd backend && npm install && npx prisma generate
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: docusign-db
          property: connectionString

  - type: web
    name: docusign-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://docusign-backend.onrender.com

databases:
  - name: docusign-db
    databaseName: docusign
    user: docusign
    plan: free
